using System.Linq;
using UnityEngine;

namespace AgarthaLib.MonoBehavior
{
    public class MonoSingleton<T> : AgarthanBehaviour where T : MonoSingleton<T>
    {
        private static T _instance;
        public static T Instance
        {
            get
            {
                _instance = _instance ?? FindObjectsByType<T>(FindObjectsInactive.Include, FindObjectsSortMode.InstanceID).FirstOrDefault();
                _instance = _instance ?? new GameObject() { name = $"[AutoGenerated] {typeof(T).Name}" }.AddComponent<T>();
                return _instance;
            }
        }

        protected virtual void Awake()
        {
            if (_instance != null && _instance != (T)this)
            {
                Destroy(_instance);
                _instance = (T)this;
            }
        }
    }
}