using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace AgarthaLib.MonoBehavior.Unity
{
    [InitializeOnLoad] public static class LayerEnumGenerator
    {
        private const string _name = "GlobalLayers";
        private const string _filePath = "Assets/" + _name + ".cs";

        static LayerEnumGenerator()
        {
            EditorApplication.projectChanged += GenerateEnum;
        }

        [MenuItem("AgarthaLib / Tools / Generate Global Layer Enum")]
        public static void GenerateEnum()
        {
            var sb = new StringBuilder();
            var origin = $"{typeof(LayerEnumGenerator).Namespace}.{typeof(LayerEnumGenerator).Name}";
            sb.AppendLine($"// This file is automatially generated by {origin}");
            sb.AppendLine($"public enum {_name}");
            sb.AppendLine("{");

            for (int i = 0; i < 32; i++)
            {
                var layerToName = LayerMask.LayerToName(i);
                if (!string.IsNullOrEmpty(layerToName))
                {
                    var name = SanitizeName(layerToName);
                    sb.AppendLine($"\t{name} = {i},");
                }
            }

            sb.AppendLine("}");

            var currentContent = File.Exists(_filePath) ? File.ReadAllText(_filePath) : string.Empty;
            if (currentContent != sb.ToString())
            {
                File.WriteAllText(_filePath, sb.ToString());
                AssetDatabase.Refresh();
            }
        }

        private static string SanitizeName(string name)
            => name.Replace(" ", "").Replace("-", "");
    }
}